pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: gueldenstone/gotmail_exporter
      platforms: "linux/amd64"
      auto_tag: true
    when:
      event: [push, tag]
  notify:
    image: gueldenstone/woodpecker-shoutrrr
    settings:
      url:
        from_secret: shoutrrr_url
      title: "gotmail_exporter deployed"
      message: "testing the new plugin"
