pipeline:
  notify:
    image: gueldenstone/woodpecker-shoutrrr
    settings:
      url:
        from_secret: shoutrrr_url
      title: "gotmail_exporter deployed"
      message: "${CI_BUILD_STATUS}: '${CI_COMMIT_LINK}' from ${CI_COMMIT_AUTHOR}\n\n${CI_BUILD_LINK}"
depends_on:
  - build
runs_on: [success, failure]
skip_clone: true
